version: '3'

services:
  companies:
    image: boalbert/companiesapi:v1
    restart: always
    ports:
      - 5050:5050
    networks:
      - lianet
    depends_on:
      - maria_db
    container_name: companies
    hostname: companies

  opportunities:
    image: boalbert/opportunities:v1
    restart: always
    ports:
      - 5053:5053
    networks:
      - lianet
    depends_on:
      - maria_db
    container_name: opportunities
    hostname: opportunities

  contextinfo:
    image: boalbert/contextinfo:v1
    restart: always
    ports:
      - 5052:5052
    networks:
      - lianet
    depends_on:
      - maria_db
    container_name: contextinfo
    hostname: contextinfo

  contacts:
    image: boalbert/contactapi:v1
    restart: always
    ports:
      - 5051:5051
    networks:
      - lianet
    depends_on:
      - maria_db
    container_name: contacts
    hostname: contacts

  userendpoint:
    image: boalbert/userendpointapi:v2
    restart: always
    ports:
      - 5054:5054
    networks:
      - lianet
    depends_on:
      - companies
      - opportunities
      - contextinfo
      - contacts
      - maria_db
    container_name: userendpoint
    hostname: userendpoint

  maria_db:
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    networks:
      - lianet
    environment:
      MYSQL_DATABASE: lia-leads
      MYSQL_USER: root
      MYSQL_PASSWORD: 16RutValter
      MYSQL_ROOT_PASSWORD: 16RutValter
    container_name: maria_db
    hostname: maria_db

networks:
  lianet: