version: '3.9'

services:
  companies:
    build: .\CompaniesAPI\.
    restart: always
    ports:
      - 5050:5050
    depends_on:
      - maria_db
    container_name: companies
    hostname: companies

  opportunities:
    build: .\OpportunitiesAPI\.
    restart: always
    ports:
      - 5053:5053
    depends_on:
      - maria_db
    container_name: opportunities
    hostname: opportunities

  contextinfo:
    build: .\ContextInformationAPI\.
    restart: always
    ports:
      - 5052:5052
    depends_on:
      - maria_db
    container_name: contextinfo
    hostname: contextinfo

  contacts:
    build: .\ContactAPI\.
    restart: always
    ports:
      - 5051:5051
    depends_on:
      - maria_db
    container_name: contacts
    hostname: contacts

  userendpoint:
    build: .\UserEndPointAPI\.
    restart: always
    ports:
      - 5054:5054
    depends_on:
      - companies
      - opportunities
      - contextinfo
      - contacts
      - maria_db
    container_name: userendpoint
    hostname: userendpoint

  maria_db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lia-leads
      MYSQL_PASSWORD: 16RutValter
      MYSQL_ROOT_PASSWORD: 16RutValter
    container_name: maria_db
    hostname: maria_db